---
title: "Data Visualization"
author: "Binod Jung Bogati"
date: "4/18/2020"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	message = FALSE,
	warning = FALSE
)
```

### Loading library

You can load tidyverse packages instead of individual packages like readr, ggplot2, tidyr and dplyr for this report.

```{r}
# install.packages("tidyverse")
library(tidyverse)

# library(readr)
# library(ggplot2)
# library(tidyr)
# library(dplyr)
```


### Data Load

Here, we load extracted csv data (pdf) from government site.

```{r}
nepal_data <- read_csv("nepal_data.csv")
nepal_data
```

### Data Transform

Here, we select, pivot and reorder our data.

```{r}
clean_covidnp_data <- nepal_data %>% 
  select(1:7) %>%  # ctrl + shift + m
  pivot_longer(
    cols = 1:7, 
    names_to = "cases", 
    values_to = "number"
  )  %>% 
  mutate(cases = fct_reorder(cases, number)) %>% 
  arrange(desc(number))

clean_covidnp_data
```

### Visualize

We use ggplot2 to visualize the barplot.

```{r}
ggplot(clean_covidnp_data, aes(x = cases, y = number)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  labs(y = "Cases Number", x = "", title = "Cases of Nepal")
```

### SAARC - Data Load 

```{r}
saarc <- read_csv("saarc_data.csv")
```

```{r}
ggplot(saarc , aes(x = country, y = total_cases)) +
 geom_bar(stat = "identity") +
  coord_flip() +
  labs(y = "Cases Number", x = "", title = "Cases of Nepal") 
```

### Credits

This report is made by R Markdown.